### ISSUE TITLE
Problems since 1.0.30001561 release

### ISSUE THREAD

**Issue by fhickeyipu** [browserslist/caniuse-lite#122] opened 2023-11-17 21:09 UTC
Our React app started having problems mysteriously.  No problems running locally with yarn start.  The production build would complete successfully, but while running the app we get strange errors about things being undefined or used before initialization.  It seems like somehow, caniuse-lite 1.0.30001561 is causing changes in the resulting code of our production builds.  

For example, with 1.0.30001559, here is what a particular function looks like at run time:

![image](https://github.com/browserslist/caniuse-lite/assets/151239108/d81ae9a5-b499-415e-87c5-dec177ff1d54)

This is from react-onclickoutside code, not ours.  In the image above, you should see that handleClickOutside looks like a regular function with a prototype and constructor.

With the only change being caniuse-lite 1.0.30001561 instead of 1.0.30001559, the same function looks like this at run time:

![image](https://github.com/browserslist/caniuse-lite/assets/151239108/90768018-90e2-4c6b-b2f3-70fb691f80ae)

In this version, handleClickOutside is represented as an arrow function and there is no prototype.  This ends up resulting in errors like this:

![image](https://github.com/browserslist/caniuse-lite/assets/151239108/cd09365c-4fdf-4f89-8b50-4b8d92e6225f)

At first, we thought the problem was with react-onclickoutside, but other parts of our app are also getting strange errors and I was able to narrow down that the issues started with the release of caniuse-lite 1.0.30001561.  Is anybody else having issues like this?

**Comment by ai** [comment] 2023-11-17 22:54
Very likely that the problem is coming from polyfills.

`camiuse-lite` updates changes target browsers in Browserslist queries like `last 2 versions`. It changes what polyfills will be added by Babel.

On many boilerplates there are different target browsers for production and development.

I suggest running `npx browserslist` before and after update to check browsers difference and then create a solid policy about target browsers.

**Comment by ai** [comment] 2023-11-17 22:55
I am closing this issue since stacktrace doesn’t have `browserslist` or `camiuse-lite` and environment debugging is a commercial work and not a community help.

**Closed by ai** 2023-11-17 22:54 UTC
